name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Terraform Init & Validate
      run: terraform init && terraform validate

    - name: Run tfsec scan
      uses: aquasecurity/tfsec-action@v1.0.0

    - name: Build Docker Image
      run: docker build -t my-app .

    - name: Scan Docker with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: my-app
